#!/usr/bin/env node

var exec = require('child_process').exec;

var args = process.argv.slice(2),
    create = false,
    input, output, dogeify, dogeified;

if (!!~['--help', '-h'].indexOf(args[0])) {
  console.log(
    'Commands:\r\n  --dogeify, -d: dogeify\r\n  --create, -c: ' +
    'create a branch (also aliased as -b to be able to create shell `alias gco=branchify`)' +
    '\r\n\r\nExample: branchify -c my awesome branch'
  );
  return;
}

if (!!~['--dogeify', '-d', '-cd', '-dc'].indexOf(args[0])) {
  if (!!~['-cd', '-dc'].indexOf(args[0])) create = true;
  args.shift();

  dogeify = ['wow', 'such', 'very', 'much', 'many', 'so', 'amaze', 'do want', 'good'];
  dogeified = [];

  for (var _i = 0; _i < args.length; _i++) {
    dogeified.push(dogeify[_i]);
    dogeified.push(args[_i]);
  }

  dogeified.push('wow');
  args = dogeified;
}

if (!!~['--create', '-c', '-b'].indexOf(args[0])) {
  create = true;
  args.shift();
}

input = args.join('-');
output = input.toLowerCase().replace(/[\s\?\+\/\\\.\[\]\{\}~±§!@#$%^&*()=⁄€‹›ﬁ‡°·¡™£¢∞¶•ªº–≠«»÷<>≤≥¿;:|"'’`_,]/g, '');

if (!create) {
  console.log(output);
}
else {
  exec('git checkout -b ' + output);
}
