#!/usr/bin/env node

var args = process.argv.slice(2);

if (args[0] === 'dogeify') {
  args.shift();

  var dogeify = ['wow', 'such', 'very', 'much', 'many', 'so', 'amaze', 'do want', 'good'];
  var dogeified = [];

  for (var _i = 0; _i < args.length; _i++) {
    dogeified.push(dogeify[_i]);
    dogeified.push(args[_i]);
  }

  dogeified.push('wow');
  args = dogeified;
}

if (args[0] === 'dashify') {
  args.shift();
  var input = args.join('-');
  var output = input.toLowerCase().replace(/[\s\?\+\/\\\.\[\]\{\}~`±§!@#$%^&*()=⁄€‹›ﬁ‡°·¡™£¢∞¶•ªº–≠«»÷<>≤≥¿;:|"'_,]/g, '');
}
else {
  var input = args.join(' ');
  var output = input.toLowerCase().replace(/[\s\?\+\/\\\.\[\]\{\}~`±§!@#$%^&*()=⁄€‹›ﬁ‡°·¡™£¢∞¶•ªº–≠«»÷<>≤≥¿;:|"'_,\-]/g, '');
}

console.log(output);
